### PR TITLE
Valantic ci

### PR DESCRIPTION
**Pull request by Klizzy**
TBC - Valantic CEC corporate identity styling

### CODE REVIEW

**Comment by MonksterFX** [comment]
@Klizzy all three styles are implemented. Feel free to provide feedback. Probably we should also refresh the styling of the examples, but this would be a different task.

**Comment by MonksterFX** [comment]
Hey i did split all the different slide scss in single files, reworked the theme main file so that is easy customizable and hides all the imports for the components. You only have to copy a the current theme now and change some variables, the rest is set automatically. It works for white (simple)/dark and color theme. I added all three as default style to select from. 

About the layout of the example slides we should rework that, it is not working on big screens properly. To avoid the scss battle we probably should add tailwind. Than we could avoid all that overhead with styling etc. because we could theme directly in tailwind. But for now this should work. Sorry that this got slighty big. Tried to be backwards compatible.

**Review by Klizzy — COMMENTED** [review]
@MonksterFX The different themes were a good idea and they look pretty good!
My only suggestion would be the replacement of the `mountains01.jpg` background file. Do you know if and where we have the valantic CI images, like the background with the bubbles? I also can replace it myself, but i don't know were we have the images 😅

**Comment by Klizzy** [comment]
> Hey i did split all the different slide scss in single files, reworked the theme main file so that is easy customizable and hides all the imports for the components. You only have to copy a the current theme now and change some variables, the rest is set automatically. It works for white (simple)/dark and color theme. I added all three as default style to select from.
> 
> About the layout of the example slides we should rework that, it is not working on big screens properly. To avoid the scss battle we probably should add tailwind. Than we could avoid all that overhead with styling etc. because we could theme directly in tailwind. But for now this should work. Sorry that this got slighty big. Tried to be backwards compatible.

@MonksterFX yeah the demo slides don't need to be made compatible in this context. The Example slides within `index.html` are usually enough, but the integration for tailwind sound pretty interesting for further tasks!

**Comment by MonksterFX** [comment]
I found some but they does not really fit to our topics. They are more industrial/networking focused. I will ask for other stuff, I knew some stuff is existing. Also probably the logo should be on the top right?

**Comment by Klizzy** [comment]
@MonksterFX thanks for looking into the background image topic. The logo don’t has to be on the BG image, because we have it already at the bottom on each slide. But if the logo is already included we can keep that to.
I think we have the bubble BG in some PowerPoint templates somewhere

**Comment by Klizzy** [comment]
@MonksterFX i found one of the PowerPoint template BG Images. I think this one would be good on the initial slide and the second one as BG images for all regular pages. What do you think?
bg-start
bg-default

**Comment by MonksterFX** [comment]
That should fit! Do you update the branch with the pictures? Or should I finalize it.

**Comment by Klizzy** [comment]
@MonksterFX i could do that, but i think the logo on the bottom on echt pages needs maybe to be removed or within the image and tested with the different themes you recently created. Just give me a ping, if you have currently a high workload. Otherwise i'll try that.

**Comment by Klizzy** [comment]
hey @MonksterFX ,

i added the first valantic image, which i screenshot from our powerpoint slides. I removed the top right valantic logo in the image, but i you look closely the modification can be seen. My photo edit skills are pretty crappy 😅
I think it can be done better in the future, maybe even with a higher resolution of the picture. I struggled with correct implementation of the bg image for all slides, so i simple made it trough inline css.

Additionally i have created more demo pages.

I'll merge the current state to master, because i need the base in my presentation at the end of the week. We can further improve this repo in the upcoming Friday sessions.

Current state can be seen here: https://val-valantic-ci.surge.sh

**Comment by MonksterFX** [comment]
🙌 If you need improvments just asign me a ticket and i will habe a look into it.

**Pull request merged**
